import React from 'react';
import './HotelMatch.css';

function HotelMatch() {
  return (
    <div className="hotel-match">
      <header className="header">
        <div className="title">Law Enforcement Portal</div>
        <nav className="navigation">
          <a href="/home">Home</a>
          <a href="/cases">Cases</a>
        </nav>
      </header>

      <main className="content">
        <section className="hotel-room-image">
          <h2>Hotel Room Image</h2>
          {/* Placeholder for the hotel room image */}
          <div className="image-placeholder"></div>
        </section>

        <section className="matched-hotels">
          <h2>Matched Hotels</h2>
          {/* List of matched hotels */}
          {/* This should be generated by mapping through an array of hotel data */}
          <div className="hotel-list">
            <div className="hotel">Hotel A - Probability: 95%</div>
            <div className="hotel">Hotel B - Probability: 92%</div>
            <div className="hotel">Hotel C - Probability: 88%</div>
            <div className="hotel">Hotel D - Probability: 85%</div>
            <div className="hotel">Hotel E - Probability: 80%</div>
          </div>
        </section>

        <section className="your-cases">
          <h2>Your Cases</h2>
          <div className="cases-list">
            {/* This should also be generated dynamically */}
            <div className="case">Case 1 - In progress</div>
            <div className="case">Case 2 - Open</div>
            <div className="case">Case 3 - Closed</div>
            <div className="case">Case 4 - On hold</div>
            <div className="case">Case 5 - In progress</div>
          </div>
        </section>
      </main>

      <footer className="footer">
        © 2022 Law Enforcement Portal. All rights reserved.
      </footer>
    </div>
  );
}

export default HotelMatch;
